---
- name: horse vim - download vim
  apt: name=vim update_cache=yes
  sudo: yes

- name: horse vim - make sure bundle directory exists
  action: file path=~/.vim/bundle state=directory

- name: horse vim - checkout vundle repo
  git: repo=https://github.com/gmarik/vundle.git
       dest=~/.vim/bundle/vundle

- name: horse vim - checkout repo
  git: repo=https://github.com/JBKahn/horse.vim.git
       dest=~/horse.vim

- name: horse vim - copy .vimrc file
  file: src=~/horse.vim/.vimrc dest=~/.vimrc mode=0755 state=link

- name: horse vim - copy .vimrc.bundles file
  file: src=~/horse.vim/.vimrc.bundles dest=~/.vimrc.bundles mode=0755 state=link

- name: horse vim - make sure vim colors directory exists
  action: file path=~/.vim/colors state=directory

- name: horse vim - copy color to config to avoid error
  copy: src=base16-default.vim dest=~/.vim/colors/base16-default.vim mode=0755

- name: horse vim - run bundle install
  command: vim +BundleInstall +qall
